services:
  redis:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: redis
    environment:
      - REDIS_PASS=${REDIS_PASS}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  redis_data:
