services:
  redis:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: redis
    env_file:
      - .redis.env
    volumes:
      - redis_data:/data
    ports:
      - "${PUBLIC_PORT}:6379"

volumes:
  redis_data:
